# Dockerfile.backend.dev (Développement)
FROM node:18-alpine

WORKDIR /app

# Copier package.json
COPY backend/package*.json ./

# Installer les dépendances
RUN npm install

# Copier le répertoire backend complet
COPY backend/ ./backend/

# Créer un utilisateur non-root
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 && \
    chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 3000

# Commande pour développement
#CMD ["sh", "-c", "cd /app/backend && npm run dev"]
CMD [ "npx", "nodemon", "/app/backend/src/app.js" ]